# This workflow will deploy source code on Cloud Run when a commit is pushed to
# the "main" branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Cloud Build (cloudbuild.googleapis.com)
#    - Cloud Run (run.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Cloud Run Source Developer (roles/run.sourceDeveloper)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources.
#
# 3. Change the values in the "env" block to match your values.

name: "Deploy to Cloud Run from Source"

on:
push:
  branches: [main]

env:
PROJECT_ID: "laparirie-ticket-dev" # TODO: update to your Google Cloud project ID
REGION: "asia-east1" # TODO: update to your region
SERVICE: "laparirie-ticket-dev" # TODO: update to your service name
DOCKER_IMAGE_URL: asia-east1-docker.pkg.dev/laparirie-ticket-dev/custom-fastapi/custom-fastapi
PROVIDER: "projects/624402969975/locations/global/workloadIdentityPools/github-action/providers/github-actions"
SERVICE_ACCOUNT: "github-actions@laparirie-ticket-dev.iam.gserviceaccount.com"

jobs:
deploy:
  runs-on: "ubuntu-latest"

  permissions:
    contents: "read"
    id-token: "write"

  steps:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secret.GCP_SA_KEY }}"
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile.prod .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated
